[package]
name = "codlinux"
version = "0.9.1"
edition = "2024"

[dependencies]
chrono = "0.4.40"
compile-time = "0.2.0"
eframe = "0.31.1"
sysinfo = "0.34.2"

[profile.release]
panic = "abort"
lto = "fat"
